apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crystal-code-quest

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml

images:
  - name: crystal-code-quest
    newTag: "20260731-045611"
