apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crystal-code-quest-data
  namespace: crystal-code-quest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
