apiVersion: v1
kind: Secret
metadata:
  name: crystal-code-quest
  namespace: crystal-code-quest
type: Opaque
stringData:
  # Replace this with a strong, randomly generated 32-byte hex secret.
  # Example: openssl rand -hex 32
  session-secret: "REPLACE_WITH_A_32_BYTE_HEX_SECRET"
