apiVersion: v1
kind: Service
metadata:
  name: crystal-code-quest
  namespace: crystal-code-quest
spec:
  selector:
    app: crystal-code-quest
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
